---

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate
  - pip install -Ur requirements.txt
  - echo isort $(isort --version-number)
  - black --version
  - flake8 --version
  - pylint --version

build:
  image: python:3.11
  stage: build
  except:
    - tags
  script:
    - echo check ...
    - isort --check --diff helloworld/*.py tests/*.py
    - black --check helloworld/*.py tests/*.py
    - pylint helloworld/*.py tests/*.py
    - echo test ...
    - pytest -v
        --html=cover/unittests.html
        --cov=helloworld
        --cov-report=html:cover
        tests/*.py
    - echo docs ...
    - (cd docs; make html)
    - echo run ...
    - python -m helloworld -h
    - python -m helloworld --version
    - python -m helloworld --log DEBUG
  artifacts:
    paths:
      - target

pages:
  image: alpine
  stage: deploy
  only:
    - master
  except:
    - tags
  before_script:
    - echo Copying artifacts from target/docs to public
  script:
    - mv target/docs public
  artifacts:
    paths:
      - public
